name = "j1shen-visitor-stats"
main = "src/index.js"
compatibility_date = "2026-06-14"

[vars]
ALLOWED_ORIGIN = "https://j1shen.github.io"

[[d1_databases]]
binding = "DB"
database_name = "j1shen-visitor-stats"
database_id = "bcd043ce-d74b-4bf7-9a70-53fdae4c486e"
